[package]
name = "material-iced"
description = "Material Design 3 widgets and theming for Iced"
readme = "../README.md"
repository = "https://git.nuros.org/iced_material/iced_material"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = ["x11", "wayland", "thread-pool"]
roboto = []
x11 = ["iced/x11"]
wayland = ["iced/wayland"]
thread-pool = ["iced/thread-pool"]

[dependencies]
iced = { workspace = true, features = ["advanced", "canvas", "svg"] }
serde_json.workspace = true
unicode-segmentation = "1"

[dev-dependencies]
iced = { workspace = true, features = ["advanced", "wgpu", "tiny-skia", "x11", "wayland", "thread-pool", "web-colors", "crisp"] }
iced_runtime = "0.14.0"

[[example]]
name = "minimal"
required-features = ["roboto"]
